version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: jobeet-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=jobeet
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - 3306:3306

    webserver:
        build:
            context: .
            dockerfile: docker/ci/nginx/Dockerfile
        container_name: jobeet-webserver
        working_dir: /application
        ports:
            - 80:80

    php-fpm:
        build:
            context: .
            dockerfile: docker/dev/php-fpm/Dockerfile
        container_name: jobeet-php-fpm
        working_dir: /application
        environment:
            - XDEBUG_CONFIG=idekey=PHPSTORM
            - PHP_IDE_CONFIG=serverName=jobeet
