version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=10.0.1
            pip install docker-compose==1.19.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run php-fpm php bin/phpunit

      - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag dockerapp_php-fpm $DOCKER_HUB_USER_ID/jobeet:$CIRCLE_SHA1
            docker tag dockerapp_php-fpm $DOCKER_HUB_USER_ID/jobeet:latest
            docker push $DOCKER_HUB_USER_ID/jobeet:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/jobeet:latest
